import type { Maker, Medium, Opacity, Paint } from './types.ts'

const WC: Medium[] = ['watercolour']
const GOUACHE: Medium[] = ['watercolour', 'gouache']
const BODY: Medium[] = ['gouache', 'acrylic', 'oil']
const ALL: Medium[] = ['watercolour', 'gouache', 'acrylic', 'oil']

type Row = readonly [id: string, name: string, pigment: string, hex: string, opacity: Opacity, mediums?: Medium[]]

function scattering(opacity: Opacity): number {
  if (opacity === 'transparent') return 0.26
  if (opacity === 'semi') return 0.48
  return 0.84
}

function expand(maker: Maker, rows: readonly Row[]): Paint[] {
  const fallback = maker === 'daniel-smith' || maker === 'winsor-newton' ? ALL : WC
  return rows.map(([id, name, pigment, hex, opacity, mediums]) => ({
    id,
    name,
    pigment,
    hex,
    opacity,
    scattering: scattering(opacity),
    mediums: mediums ?? fallback,
    maker,
  }))
}

const STUDIO: Row[] = [
  ['hansa-yellow', 'Hansa Yellow', 'PY3', '#F4D24A', 'semi', ALL],
  ['cadmium-yellow', 'Cadmium Yellow', 'PY35', '#F0C01A', 'opaque', ALL],
  ['naples-yellow', 'Naples Yellow', 'PY41', '#E6D08A', 'opaque', BODY],
  ['yellow-ochre', 'Yellow Ochre', 'PY43', '#C4963B', 'opaque', ALL],
  ['raw-sienna', 'Raw Sienna', 'PBr7', '#C4843C', 'semi', ALL],
  ['cadmium-orange', 'Cadmium Orange', 'PO20', '#E87A2E', 'opaque', ALL],
  ['cadmium-red', 'Cadmium Red', 'PR108', '#E03C28', 'opaque', ALL],
  ['pyrrole-red', 'Pyrrole Red', 'PR254', '#D42B2B', 'opaque', BODY],
  ['alizarin-crimson', 'Alizarin Crimson', 'PR83', '#9B1B32', 'transparent', ALL],
  ['quinacridone-rose', 'Quinacridone Rose', 'PV19', '#C13B6A', 'transparent', ALL],
  ['quinacridone-magenta', 'Quinacridone Magenta', 'PR122', '#B01A5B', 'transparent', WC],
  ['burnt-sienna', 'Burnt Sienna', 'PBr7', '#8F4B2E', 'semi', ALL],
  ['burnt-umber', 'Burnt Umber', 'PBr7', '#5A3317', 'semi', ALL],
  ['raw-umber', 'Raw Umber', 'PBr7', '#6E4B2A', 'semi', ALL],
  ['ultramarine', 'Ultramarine Blue', 'PB29', '#3A4EA0', 'semi', ALL],
  ['cobalt-blue', 'Cobalt Blue', 'PB28', '#2E5FA3', 'semi', ALL],
  ['cerulean-blue', 'Cerulean Blue', 'PB35', '#2B8CBA', 'opaque', ALL],
  ['phthalo-blue', 'Phthalo Blue', 'PB15:3', '#08457E', 'transparent', ALL],
  ['prussian-blue', 'Prussian Blue', 'PB27', '#0A2F4A', 'transparent', ['watercolour', 'acrylic', 'oil']],
  ['phthalo-green', 'Phthalo Green', 'PG7', '#0B6B54', 'transparent', ALL],
  ['viridian', 'Viridian', 'PG18', '#3F7F6E', 'transparent', ALL],
  ['sap-green', 'Sap Green', 'PG8', '#4C7A2F', 'semi', ['watercolour', 'gouache', 'oil']],
  ['dioxazine-purple', 'Dioxazine Purple', 'PV23', '#4A2A6A', 'transparent', ALL],
  ['paynes-gray', "Payne's Gray", 'PB29 + PBk9', '#3E4A56', 'semi', ['watercolour', 'gouache', 'acrylic']],
  ['ivory-black', 'Ivory Black', 'PBk9', '#1A1A1A', 'semi', ALL],
  ['titanium-white', 'Titanium White', 'PW6', '#F6F3EC', 'opaque', BODY],
  ['chinese-white', 'Chinese White', 'PW4', '#F3F0E8', 'opaque', GOUACHE],
]

const DANIEL_SMITH: Row[] = [
  ['ds-buff-titanium', 'Buff Titanium', 'PW6', '#E8D9C0', 'opaque'],
  ['ds-hansa-yellow-light', 'Hansa Yellow Light', 'PY3', '#F6E24C', 'semi'],
  ['ds-hansa-yellow-medium', 'Hansa Yellow Medium', 'PY97', '#F0C93A', 'semi'],
  ['ds-hansa-yellow-deep', 'Hansa Yellow Deep', 'PY65', '#E8A318', 'semi'],
  ['ds-nickel-titanate-yellow', 'Nickel Titanate Yellow', 'PY53', '#E8E07A', 'opaque'],
  ['ds-bismuth-vanadate-yellow', 'Bismuth Vanadate Yellow', 'PY184', '#F0D22A', 'opaque'],
  ['ds-new-gamboge', 'New Gamboge', 'PY97 + PY110', '#E59B14', 'transparent'],
  ['ds-indian-yellow', 'Indian Yellow', 'PY110 + PY150', '#E39A18', 'transparent'],
  ['ds-nickel-azo-yellow', 'Nickel Azo Yellow', 'PY150', '#D4A018', 'transparent'],
  ['ds-quinacridone-gold', 'Quinacridone Gold', 'PO48 + PY150', '#C47A1A', 'transparent'],
  ['ds-quinacridone-deep-gold', 'Quinacridone Deep Gold', 'PO48', '#B45E16', 'transparent'],
  ['ds-cadmium-yellow-medium-hue', 'Cadmium Yellow Medium Hue', 'PY53 + PY151 + PY83', '#F0C01A', 'opaque'],
  ['ds-lemon-yellow', 'Lemon Yellow', 'PY175', '#F4E24A', 'semi'],
  ['ds-naples-yellow', 'Naples Yellow', 'PBr24', '#E6D08A', 'opaque'],
  ['ds-pyrrol-orange', 'Pyrrol Orange', 'PO73', '#E86A1E', 'semi'],
  ['ds-permanent-orange', 'Permanent Orange', 'PO62', '#E86820', 'semi'],
  ['ds-mayan-orange', 'Mayan Orange', 'PY216', '#E06A28', 'semi'],
  ['ds-cadmium-orange-hue', 'Cadmium Orange Hue', 'PO20', '#E87A2E', 'opaque'],
  ['ds-pyrrol-scarlet', 'Pyrrol Scarlet', 'PR255', '#E23A28', 'semi'],
  ['ds-organic-vermilion', 'Organic Vermilion', 'PR188', '#E04532', 'semi'],
  ['ds-quinacridone-coral', 'Quinacridone Coral', 'PR209', '#E0564A', 'transparent'],
  ['ds-pyrrol-red', 'Pyrrol Red', 'PR254', '#D42B2B', 'semi'],
  ['ds-cadmium-red-medium-hue', 'Cadmium Red Medium Hue', 'PR108', '#E03C28', 'opaque'],
  ['ds-permanent-alizarin-crimson', 'Permanent Alizarin Crimson', 'PR177', '#8E1D32', 'transparent'],
  ['ds-alizarin-crimson', 'Alizarin Crimson', 'PR83', '#9B1B32', 'transparent'],
  ['ds-anthraquinoid-red', 'Anthraquinoid Red', 'PR177', '#A02030', 'transparent'],
  ['ds-quinacridone-rose', 'Quinacridone Rose', 'PV19', '#C13B6A', 'transparent'],
  ['ds-quinacridone-magenta', 'Quinacridone Magenta', 'PR122', '#B01A5B', 'transparent'],
  ['ds-quinacridone-pink', 'Quinacridone Pink', 'PV19', '#D45A86', 'transparent'],
  ['ds-quinacridone-violet', 'Quinacridone Violet', 'PV19', '#8A2A62', 'transparent'],
  ['ds-quinacridone-purple', 'Quinacridone Purple', 'PV55', '#6A2460', 'transparent'],
  ['ds-opera-pink', 'Opera Pink', 'PR122 + BV10', '#FF4A8A', 'transparent'],
  ['ds-potters-pink', "Potter's Pink", 'PR233', '#C4787A', 'semi'],
  ['ds-carbazole-violet', 'Carbazole Violet', 'PV23', '#4A2A6A', 'transparent'],
  ['ds-cobalt-violet', 'Cobalt Violet', 'PV14', '#8A4A8A', 'semi'],
  ['ds-imperial-purple', 'Imperial Purple', 'PV15', '#5A2A6A', 'semi'],
  ['ds-moonglow', 'Moonglow', 'PG18 + PV19 + PB29', '#4A3A5A', 'transparent'],
  ['ds-shadow-violet', 'Shadow Violet', 'PV15 + PBk11', '#4A3548', 'semi'],
  ['ds-wisteria', 'Wisteria', 'PW6 + PV15 + PB29', '#B8A0C8', 'opaque'],
  ['ds-lavender', 'Lavender', 'PW6 + PV15 + PB29', '#8A8AB8', 'opaque'],
  ['ds-rose-of-ultramarine', 'Rose of Ultramarine', 'PV15 + PB29', '#7A4A8A', 'semi'],
  ['ds-ultramarine-blue', 'Ultramarine Blue', 'PB29', '#3A4EA0', 'semi'],
  ['ds-french-ultramarine', 'French Ultramarine', 'PB29', '#3D4F9F', 'semi'],
  ['ds-cobalt-blue', 'Cobalt Blue', 'PB28', '#2E5FA3', 'semi'],
  ['ds-phthalo-blue-gs', 'Phthalo Blue (Green Shade)', 'PB15:3', '#08457E', 'transparent'],
  ['ds-phthalo-blue-rs', 'Phthalo Blue (Red Shade)', 'PB15', '#1A3A8C', 'transparent'],
  ['ds-cerulean-blue', 'Cerulean Blue', 'PB35', '#2B8CBA', 'opaque'],
  ['ds-cerulean-blue-chromium', 'Cerulean Blue Chromium', 'PB36', '#2A7CA8', 'opaque'],
  ['ds-prussian-blue', 'Prussian Blue', 'PB27', '#0A2F4A', 'transparent'],
  ['ds-indigo', 'Indigo', 'PB60 + PBk6 + PV19', '#1A2A4A', 'semi'],
  ['ds-indanthrone-blue', 'Indanthrone Blue', 'PB60', '#1A2A58', 'transparent'],
  ['ds-lunar-blue', 'Lunar Blue', 'PB15 + PBk11', '#3A5A6A', 'semi'],
  ['ds-sodalite-genuine', 'Sodalite Genuine', 'genuine', '#2A3A50', 'semi'],
  ['ds-cobalt-turquoise', 'Cobalt Turquoise', 'PB36', '#1A8A8A', 'opaque'],
  ['ds-cobalt-teal-blue', 'Cobalt Teal Blue', 'PG50', '#2AA0A0', 'opaque'],
  ['ds-phthalo-turquoise', 'Phthalo Turquoise', 'PB16', '#0A6A78', 'transparent'],
  ['ds-manganese-blue-hue', 'Manganese Blue Hue', 'PB15', '#1A8AB8', 'transparent'],
  ['ds-phthalo-green-bs', 'Phthalo Green (Blue Shade)', 'PG7', '#0B6B54', 'transparent'],
  ['ds-phthalo-green-ys', 'Phthalo Green (Yellow Shade)', 'PG36', '#1A7A3A', 'transparent'],
  ['ds-viridian', 'Viridian', 'PG18', '#3F7F6E', 'transparent'],
  ['ds-sap-green', 'Sap Green', 'PG7 + PY150', '#4C7A2F', 'semi'],
  ['ds-hookers-green', "Hooker's Green", 'PG36 + PO49 + PY3', '#2F6A3C', 'semi'],
  ['ds-undersea-green', 'Undersea Green', 'PB29 + PO49 + PY150', '#3A5A40', 'semi'],
  ['ds-cascade-green', 'Cascade Green', 'PBr7 + PG7', '#3A6A5A', 'semi'],
  ['ds-perylene-green', 'Perylene Green', 'PBk31', '#1A3A32', 'transparent'],
  ['ds-green-apatite', 'Green Apatite Genuine', 'genuine', '#4A6A3A', 'semi'],
  ['ds-serpentine-genuine', 'Serpentine Genuine', 'genuine', '#5A7A4A', 'semi'],
  ['ds-jadeite-genuine', 'Jadeite Genuine', 'genuine', '#4A7A68', 'semi'],
  ['ds-olive-green', 'Olive Green', 'PY150 + PG7 + PBk7', '#4A5A28', 'semi'],
  ['ds-green-gold', 'Green Gold', 'PY150', '#8A9A28', 'transparent'],
  ['ds-yellow-ochre', 'Yellow Ochre', 'PY43', '#C4963B', 'opaque'],
  ['ds-raw-sienna', 'Raw Sienna', 'PBr7', '#C4843C', 'semi'],
  ['ds-raw-sienna-light', 'Raw Sienna Light', 'PBr7', '#D4A04A', 'semi'],
  ['ds-monte-amiata', 'Monte Amiata Natural Sienna', 'PBr7', '#C4843C', 'semi'],
  ['ds-goethite', 'Goethite (Brown Ochre)', 'PY43', '#B8893A', 'semi'],
  ['ds-burnt-sienna', 'Burnt Sienna', 'PBr7', '#8F4B2E', 'semi'],
  ['ds-burnt-sienna-light', 'Burnt Sienna Light', 'PBr7', '#B86A40', 'semi'],
  ['ds-transparent-red-oxide', 'Transparent Red Oxide', 'PR101', '#A34528', 'transparent'],
  ['ds-quinacridone-burnt-orange', 'Quinacridone Burnt Orange', 'PO48', '#A84A28', 'transparent'],
  ['ds-quinacridone-sienna', 'Quinacridone Sienna', 'PR206', '#A8522E', 'transparent'],
  ['ds-venetian-red', 'Venetian Red', 'PR101', '#B44A3A', 'opaque'],
  ['ds-indian-red', 'Indian Red', 'PR101', '#8A3A32', 'opaque'],
  ['ds-burnt-umber', 'Burnt Umber', 'PBr7', '#5A3317', 'semi'],
  ['ds-raw-umber', 'Raw Umber', 'PBr7', '#6E4B2A', 'semi'],
  ['ds-aussie-red-gold', 'Aussie Red Gold', 'PY83 + PR101 + PR206', '#C45A28', 'semi'],
  ['ds-perylene-maroon', 'Perylene Maroon', 'PR179', '#6A2030', 'transparent'],
  ['ds-perylene-violet', 'Perylene Violet', 'PV29', '#5A2038', 'transparent'],
  ['ds-paynes-blue-gray', "Payne's Blue Gray", 'PB60 + PBk6', '#3A4A5A', 'semi'],
  ['ds-janes-grey', "Jane's Grey", 'PB29 + PBk9', '#4A5560', 'semi'],
  ['ds-lunar-black', 'Lunar Black', 'PBk11', '#2A2A2A', 'semi'],
  ['ds-neutral-tint', 'Neutral Tint', 'PBk6 + PV19', '#2C2C30', 'transparent'],
  ['ds-titanium-white', 'Titanium White', 'PW6', '#F6F3EC', 'opaque', ['gouache']],
]

const WINSOR_NEWTON: Row[] = [
  ['wn-lemon-yellow', 'Lemon Yellow', 'PY53', '#F3E25A', 'opaque'],
  ['wn-winsor-lemon', 'Winsor Lemon', 'PY175', '#F4E24A', 'semi'],
  ['wn-bismuth-yellow', 'Bismuth Yellow', 'PY184', '#F0D22A', 'opaque'],
  ['wn-cadmium-lemon', 'Cadmium Lemon', 'PY35', '#F3E03A', 'opaque'],
  ['wn-winsor-yellow', 'Winsor Yellow', 'PY154', '#F0C93A', 'semi'],
  ['wn-cadmium-yellow-pale', 'Cadmium Yellow Pale', 'PY35', '#F2D24A', 'opaque'],
  ['wn-cadmium-yellow', 'Cadmium Yellow', 'PY35', '#F0C01A', 'opaque'],
  ['wn-cadmium-yellow-deep', 'Cadmium Yellow Deep', 'PY35', '#E8A318', 'opaque'],
  ['wn-new-gamboge', 'New Gamboge', 'PY150 + PR209', '#E59B14', 'transparent'],
  ['wn-transparent-yellow', 'Transparent Yellow', 'PY150', '#E0B020', 'transparent'],
  ['wn-winsor-yellow-deep', 'Winsor Yellow Deep', 'PY65', '#E8A318', 'semi'],
  ['wn-indian-yellow', 'Indian Yellow', 'PY139', '#E39A18', 'transparent'],
  ['wn-cadmium-orange', 'Cadmium Orange', 'PO20', '#E87A2E', 'opaque'],
  ['wn-winsor-orange', 'Winsor Orange', 'PO62', '#E86820', 'semi'],
  ['wn-winsor-orange-rs', 'Winsor Orange Red Shade', 'PO73', '#E85A20', 'semi'],
  ['wn-scarlet-lake', 'Scarlet Lake', 'PR188', '#E04532', 'semi'],
  ['wn-quinacridone-red', 'Quinacridone Red', 'PR209', '#D4454A', 'transparent'],
  ['wn-winsor-red', 'Winsor Red', 'PR254', '#D42B2B', 'semi'],
  ['wn-cadmium-scarlet', 'Cadmium Scarlet', 'PR108', '#E03C28', 'opaque'],
  ['wn-cadmium-red', 'Cadmium Red', 'PR108', '#D83228', 'opaque'],
  ['wn-cadmium-red-deep', 'Cadmium Red Deep', 'PR108', '#C02828', 'opaque'],
  ['wn-winsor-red-deep', 'Winsor Red Deep', 'PR264', '#A02030', 'transparent'],
  ['wn-alizarin-crimson', 'Alizarin Crimson', 'PR83', '#9B1B32', 'transparent'],
  ['wn-permanent-alizarin-crimson', 'Permanent Alizarin Crimson', 'PR206', '#8E1D32', 'transparent'],
  ['wn-permanent-carmine', 'Permanent Carmine', 'PR176', '#9A2040', 'transparent'],
  ['wn-permanent-rose', 'Permanent Rose', 'PV19', '#C13B6A', 'transparent'],
  ['wn-rose-madder-genuine', 'Rose Madder Genuine', 'NR9', '#C45A6A', 'transparent'],
  ['wn-opera-rose', 'Opera Rose', 'PR122', '#FF4A8A', 'transparent'],
  ['wn-quinacridone-magenta', 'Quinacridone Magenta', 'PR122', '#B01A5B', 'transparent'],
  ['wn-permanent-magenta', 'Permanent Magenta', 'PV19', '#8A2A62', 'transparent'],
  ['wn-permanent-mauve', 'Permanent Mauve', 'PV16', '#6A3A6A', 'semi'],
  ['wn-cobalt-violet', 'Cobalt Violet', 'PV14', '#8A4A8A', 'semi'],
  ['wn-winsor-violet', 'Winsor Violet (Dioxazine)', 'PV23', '#4A2A6A', 'transparent'],
  ['wn-ultramarine-violet', 'Ultramarine Violet', 'PV15', '#6A4A8A', 'semi'],
  ['wn-french-ultramarine', 'French Ultramarine', 'PB29', '#3D4F9F', 'semi'],
  ['wn-ultramarine-gs', 'Ultramarine Green Shade', 'PB29', '#3A4EA0', 'semi'],
  ['wn-cobalt-blue', 'Cobalt Blue', 'PB28', '#2E5FA3', 'semi'],
  ['wn-cobalt-blue-deep', 'Cobalt Blue Deep', 'PB74', '#2A4A8A', 'semi'],
  ['wn-cerulean-blue', 'Cerulean Blue', 'PB35', '#2B8CBA', 'opaque'],
  ['wn-cerulean-blue-rs', 'Cerulean Blue Red Shade', 'PB35 + PB28', '#3A7CB0', 'opaque'],
  ['wn-winsor-blue-gs', 'Winsor Blue Green Shade', 'PB15', '#08457E', 'transparent'],
  ['wn-winsor-blue-rs', 'Winsor Blue Red Shade', 'PB15', '#1A3A8C', 'transparent'],
  ['wn-manganese-blue-hue', 'Manganese Blue Hue', 'PB15', '#1A8AB8', 'transparent'],
  ['wn-indanthrene-blue', 'Indanthrene Blue', 'PB60', '#1A2A58', 'transparent'],
  ['wn-indigo', 'Indigo', 'PB15 + PBk6 + PV19', '#1A2A4A', 'semi'],
  ['wn-prussian-blue', 'Prussian Blue', 'PB27', '#0A2F4A', 'transparent'],
  ['wn-antwerp-blue', 'Antwerp Blue', 'PB27', '#0A3A58', 'transparent'],
  ['wn-phthalo-turquoise', 'Phthalo Turquoise', 'PB16', '#0A6A78', 'transparent'],
  ['wn-cobalt-turquoise', 'Cobalt Turquoise', 'PB36', '#1A8A8A', 'opaque'],
  ['wn-cobalt-turquoise-light', 'Cobalt Turquoise Light', 'PG50', '#2AA0A0', 'opaque'],
  ['wn-cobalt-green', 'Cobalt Green', 'PG26', '#3A8A6A', 'semi'],
  ['wn-winsor-green-bs', 'Winsor Green Blue Shade', 'PG7', '#0B6B54', 'transparent'],
  ['wn-winsor-green-ys', 'Winsor Green Yellow Shade', 'PG36', '#1A7A3A', 'transparent'],
  ['wn-viridian-hue', 'Viridian Hue', 'PG7 + PG18', '#3F7F6E', 'transparent'],
  ['wn-hookers-green', "Hooker's Green", 'PG36 + PY110', '#2F6A3C', 'semi'],
  ['wn-permanent-sap-green', 'Permanent Sap Green', 'PG36', '#4C7A2F', 'semi'],
  ['wn-oxide-of-chromium', 'Oxide of Chromium', 'PG17', '#4A6A40', 'opaque'],
  ['wn-terre-verte', 'Terre Verte', 'PG23', '#5A7A62', 'semi'],
  ['wn-olive-green', 'Olive Green', 'PY110 + PG7 + PBk7', '#4A5A28', 'semi'],
  ['wn-green-gold', 'Green Gold', 'PY129', '#8A9A28', 'transparent'],
  ['wn-naples-yellow', 'Naples Yellow', 'PBr24', '#E6D08A', 'opaque'],
  ['wn-naples-yellow-deep', 'Naples Yellow Deep', 'PBr24', '#D4B06A', 'opaque'],
  ['wn-yellow-ochre-light', 'Yellow Ochre Light', 'PY42', '#D4B05A', 'opaque'],
  ['wn-yellow-ochre', 'Yellow Ochre', 'PY43', '#C4963B', 'opaque'],
  ['wn-gold-ochre', 'Gold Ochre', 'PY42', '#C48A2A', 'opaque'],
  ['wn-raw-sienna', 'Raw Sienna', 'PBr7', '#C4843C', 'semi'],
  ['wn-quinacridone-gold', 'Quinacridone Gold', 'PO48 + PY150', '#C47A1A', 'transparent'],
  ['wn-brown-ochre', 'Brown Ochre', 'PY43', '#B8893A', 'semi'],
  ['wn-burnt-sienna', 'Burnt Sienna', 'PR101', '#8F4B2E', 'semi'],
  ['wn-light-red', 'Light Red', 'PR101', '#B85A3A', 'opaque'],
  ['wn-venetian-red', 'Venetian Red', 'PR101', '#B44A3A', 'opaque'],
  ['wn-indian-red', 'Indian Red', 'PR101', '#8A3A32', 'opaque'],
  ['wn-brown-madder', 'Brown Madder', 'PR206', '#8A3A32', 'transparent'],
  ['wn-perylene-maroon', 'Perylene Maroon', 'PR179', '#6A2030', 'transparent'],
  ['wn-potters-pink', "Potter's Pink", 'PR233', '#C4787A', 'semi'],
  ['wn-caput-mortuum-violet', 'Caput Mortuum Violet', 'PR101', '#6A3040', 'opaque'],
  ['wn-perylene-violet', 'Perylene Violet', 'PV29', '#5A2038', 'transparent'],
  ['wn-burnt-umber', 'Burnt Umber', 'PBr7', '#5A3317', 'semi'],
  ['wn-raw-umber', 'Raw Umber', 'PBr7', '#6E4B2A', 'semi'],
  ['wn-vandyke-brown', 'Vandyke Brown', 'PBr7 + PBk9', '#4A3020', 'semi'],
  ['wn-sepia', 'Sepia', 'PBr7 + PBk6', '#3A2818', 'semi'],
  ['wn-perylene-green', 'Perylene Green', 'PBk31', '#1A3A32', 'transparent'],
  ['wn-davys-gray', "Davy's Gray", 'PG23 + PBk9', '#6A6A5A', 'semi'],
  ['wn-paynes-gray', "Payne's Gray", 'PB15 + PBk6', '#3E4A56', 'semi'],
  ['wn-neutral-tint', 'Neutral Tint', 'PB15 + PBk6 + PV19', '#2C2C30', 'transparent'],
  ['wn-ivory-black', 'Ivory Black', 'PBk9', '#1A1A1A', 'semi'],
  ['wn-mars-black', 'Mars Black', 'PBk11', '#1C1C1C', 'opaque'],
  ['wn-lamp-black', 'Lamp Black', 'PBk6', '#141414', 'semi'],
  ['wn-chinese-white', 'Chinese White', 'PW4', '#F3F0E8', 'opaque', GOUACHE],
  ['wn-titanium-white', 'Titanium White', 'PW6', '#F6F3EC', 'opaque', BODY],
]

export const CATALOGUE_PAINTS: Paint[] = [
  ...expand('studio', STUDIO),
  ...expand('daniel-smith', DANIEL_SMITH),
  ...expand('winsor-newton', WINSOR_NEWTON),
]
