import type { Medium, Paint } from './types.ts'

export const PAINTS: Paint[] = [
  {
    id: 'hansa-yellow',
    name: 'Hansa Yellow',
    pigment: 'PY3',
    hex: '#F4D24A',
    opacity: 'semi',
    scattering: 0.42,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'cadmium-yellow',
    name: 'Cadmium Yellow',
    pigment: 'PY35',
    hex: '#F0C01A',
    opacity: 'opaque',
    scattering: 0.86,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'naples-yellow',
    name: 'Naples Yellow',
    pigment: 'PY41',
    hex: '#E6D08A',
    opacity: 'opaque',
    scattering: 0.78,
    mediums: ['gouache', 'acrylic', 'oil'],
  },
  {
    id: 'yellow-ochre',
    name: 'Yellow Ochre',
    pigment: 'PY43',
    hex: '#C4963B',
    opacity: 'opaque',
    scattering: 0.72,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'raw-sienna',
    name: 'Raw Sienna',
    pigment: 'PBr7',
    hex: '#C4843C',
    opacity: 'semi',
    scattering: 0.55,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'cadmium-orange',
    name: 'Cadmium Orange',
    pigment: 'PO20',
    hex: '#E87A2E',
    opacity: 'opaque',
    scattering: 0.82,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'cadmium-red',
    name: 'Cadmium Red',
    pigment: 'PR108',
    hex: '#E03C28',
    opacity: 'opaque',
    scattering: 0.84,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'pyrrole-red',
    name: 'Pyrrole Red',
    pigment: 'PR254',
    hex: '#D42B2B',
    opacity: 'opaque',
    scattering: 0.7,
    mediums: ['acrylic', 'oil', 'gouache'],
  },
  {
    id: 'alizarin-crimson',
    name: 'Alizarin Crimson',
    pigment: 'PR83',
    hex: '#9B1B32',
    opacity: 'transparent',
    scattering: 0.28,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'quinacridone-rose',
    name: 'Quinacridone Rose',
    pigment: 'PV19',
    hex: '#C13B6A',
    opacity: 'transparent',
    scattering: 0.3,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'quinacridone-magenta',
    name: 'Quinacridone Magenta',
    pigment: 'PR122',
    hex: '#B01A5B',
    opacity: 'transparent',
    scattering: 0.3,
    mediums: ['watercolour', 'acrylic'],
  },
  {
    id: 'burnt-sienna',
    name: 'Burnt Sienna',
    pigment: 'PBr7',
    hex: '#8F4B2E',
    opacity: 'semi',
    scattering: 0.5,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'burnt-umber',
    name: 'Burnt Umber',
    pigment: 'PBr7',
    hex: '#5A3317',
    opacity: 'semi',
    scattering: 0.48,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'raw-umber',
    name: 'Raw Umber',
    pigment: 'PBr7',
    hex: '#6E4B2A',
    opacity: 'semi',
    scattering: 0.5,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'ultramarine',
    name: 'Ultramarine Blue',
    pigment: 'PB29',
    hex: '#3A4EA0',
    opacity: 'semi',
    scattering: 0.4,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'cobalt-blue',
    name: 'Cobalt Blue',
    pigment: 'PB28',
    hex: '#2E5FA3',
    opacity: 'semi',
    scattering: 0.58,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'cerulean-blue',
    name: 'Cerulean Blue',
    pigment: 'PB35',
    hex: '#2B8CBA',
    opacity: 'opaque',
    scattering: 0.7,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'phthalo-blue',
    name: 'Phthalo Blue',
    pigment: 'PB15:3',
    hex: '#08457E',
    opacity: 'transparent',
    scattering: 0.22,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'prussian-blue',
    name: 'Prussian Blue',
    pigment: 'PB27',
    hex: '#0A2F4A',
    opacity: 'transparent',
    scattering: 0.26,
    mediums: ['watercolour', 'acrylic', 'oil'],
  },
  {
    id: 'phthalo-green',
    name: 'Phthalo Green',
    pigment: 'PG7',
    hex: '#0B6B54',
    opacity: 'transparent',
    scattering: 0.24,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'viridian',
    name: 'Viridian',
    pigment: 'PG18',
    hex: '#3F7F6E',
    opacity: 'transparent',
    scattering: 0.32,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'sap-green',
    name: 'Sap Green',
    pigment: 'PG8',
    hex: '#4C7A2F',
    opacity: 'semi',
    scattering: 0.4,
    mediums: ['watercolour', 'gouache', 'oil'],
  },
  {
    id: 'dioxazine-purple',
    name: 'Dioxazine Purple',
    pigment: 'PV23',
    hex: '#4A2A6A',
    opacity: 'transparent',
    scattering: 0.28,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'paynes-gray',
    name: "Payne's Gray",
    pigment: 'PB29 + PBk9',
    hex: '#3E4A56',
    opacity: 'semi',
    scattering: 0.36,
    mediums: ['watercolour', 'gouache', 'acrylic'],
  },
  {
    id: 'ivory-black',
    name: 'Ivory Black',
    pigment: 'PBk9',
    hex: '#1A1A1A',
    opacity: 'semi',
    scattering: 0.34,
    mediums: ['watercolour', 'gouache', 'acrylic', 'oil'],
  },
  {
    id: 'titanium-white',
    name: 'Titanium White',
    pigment: 'PW6',
    hex: '#F6F3EC',
    opacity: 'opaque',
    scattering: 1,
    mediums: ['gouache', 'acrylic', 'oil'],
  },
  {
    id: 'chinese-white',
    name: 'Chinese White',
    pigment: 'PW4',
    hex: '#F3F0E8',
    opacity: 'opaque',
    scattering: 0.92,
    mediums: ['watercolour', 'gouache'],
  },
]

export const PAINTS_BY_ID = new Map(PAINTS.map((paint) => [paint.id, paint]))

export const DEFAULT_PALETTES: Record<Medium, string[]> = {
  watercolour: [
    'hansa-yellow',
    'yellow-ochre',
    'cadmium-red',
    'alizarin-crimson',
    'quinacridone-rose',
    'burnt-sienna',
    'burnt-umber',
    'ultramarine',
    'cerulean-blue',
    'phthalo-blue',
    'phthalo-green',
    'sap-green',
    'paynes-gray',
  ],
  gouache: [
    'hansa-yellow',
    'yellow-ochre',
    'cadmium-orange',
    'cadmium-red',
    'alizarin-crimson',
    'burnt-sienna',
    'ultramarine',
    'cerulean-blue',
    'phthalo-green',
    'dioxazine-purple',
    'ivory-black',
    'titanium-white',
  ],
  acrylic: [
    'cadmium-yellow',
    'yellow-ochre',
    'cadmium-orange',
    'pyrrole-red',
    'alizarin-crimson',
    'burnt-sienna',
    'burnt-umber',
    'ultramarine',
    'phthalo-blue',
    'phthalo-green',
    'dioxazine-purple',
    'ivory-black',
    'titanium-white',
  ],
  oil: [
    'cadmium-yellow',
    'yellow-ochre',
    'raw-sienna',
    'cadmium-red',
    'alizarin-crimson',
    'burnt-sienna',
    'burnt-umber',
    'ultramarine',
    'cobalt-blue',
    'viridian',
    'ivory-black',
    'titanium-white',
  ],
}

export function paintsForMedium(medium: Medium): Paint[] {
  return PAINTS.filter((paint) => paint.mediums.includes(medium))
}

export function defaultEnabledIds(medium: Medium): string[] {
  return [...DEFAULT_PALETTES[medium]]
}
